name: Python Flask App CI

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build-and-test:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Lint with flake8
        run: |
          pip install flake8
          flake8 VillafloresJoellen_PrelimExam.py --max-line-length=120

      - name: Run Flask app (smoke test)
        run: |
          export FLASK_APP=VillafloresJoellen_PrelimExam.py
          flask run --no-debugger --no-reload &
          sleep 10
          curl --fail http://127.0.0.1:5000/
        env:
          FLASK_ENV: development

  # Optional: Deploy job to GitHub Pages or another platform (commented out)
  # deploy:
  #   runs-on: ubuntu-latest
  #   needs: build-and-test
  #   steps:
  #     - name: Deploy step goes here
  #       run: echo "Add deployment steps for your preferred platform"
